# Generated by Django 5.2.4 on 2026-01-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0002_inventoryitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
