# Generated by Django 5.2.4 on 2026-01-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0003_customer_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
