# Generated by Django 5.2.4 on 2026-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0004_alter_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcart',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='savedcart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='savedcart',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
