# Generated by Django 5.2.4 on 2026-01-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0005_savedcart_discount_savedcart_subtotal_savedcart_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
