# Generated by Django 5.2.4 on 2026-01-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0006_stockadjustment_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_images/'),
        ),
    ]
